# Grunt aliases
---
# Build everything
build:
  - 'build:js'
  - 'build:css'
  - 'build:i18n'
# Build JavaScript from assets to production
'build:js':
  - 'browserify:build'
  - 'uglify'
'build:css':
  - 'copy:css_social_previews'
  - 'sass'
  - 'autoprefixer'
  - 'wpcss'
  - 'cssmin'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'shell:makepot_social_previews'
  - 'shell:combine-pot-files'
  - 'glotpress_download'
  - 'po2json'
  - 'i18n-clean-json'
  - 'clean:po-files'
# Check health of the project
check:
  - 'eslint'
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'
# Get the project ready for release
release:
  - 'build:css'
  - 'build:images'
  - 'release:js'
'release:js':
  - 'browserify:build'
  - 'browserify:release-es6'
  - 'uglify'
# Default task
default:
  - build
